fix: add more telemetry
salesforcecli/plugin-info pull request #33
Opened 2021-11-24 16:17 UTC by WillieRuemmele

### What does this PR do?
Adds additional telemetry events based on conversations with Eric

### What issues does this PR fix or reference?
@W-10190533@

2021-11-29 16:23 UTC, mshanemc approved these changes

2021-11-29 16:32 UTC, mshanemc requested changes

2021-11-29 16:32 UTC, mshanemc commented on src/commands/info/releasenotes/display.ts
> +        await Lifecycle.getInstance().emitTelemetry({ eventName: 'Error', Error: { message, stack } });
hmm.  We do have `EXCEPTION` as a top-level event type.

Can we try setting the value for `type` like our error stuff does?

https://github.com/salesforcecli/plugin-telemetry/blob/50248fe2da68d80fb1ab613f3ece88e2ca647bf7/src/telemetry.ts#L273

2021-11-29 16:32 UTC, mshanemc commented on src/commands/info/releasenotes/display.ts
> +        await Lifecycle.getInstance().emitTelemetry({ eventName: 'Error', Error: { message, stack } });
that's used here: https://github.com/salesforcecli/plugin-telemetry/blob/50248fe2da68d80fb1ab613f3ece88e2ca647bf7/src/hooks/telemetryPrerun.ts#L112

`eventName: 'COMMAND_ERROR'`

2021-11-30 02:31 UTC, mshanemc approved these changes

2021-11-30 16:50 UTC, iowillhoit requested changes

2021-11-30 16:50 UTC, iowillhoit commented on src/commands/info/releasenotes/display.ts
> +        await Lifecycle.getInstance().emitTelemetry({ eventName: 'FOOTER_HIDDEN' });
Hey @WillieRuemmele, I think I did a bad job explaining this one. The metric I'm wanting to collect here is how many people are actively setting the hide footer env var. This `else` will emit when someone runs a command on their machine (not with the `--hook` flag that will run in the post update hooks). Will want to make sure `isHook` and the env var are both true, something like:

```js
if (isHook) {
  if (env.getBoolean(HIDE_FOOTER)) {
    await Lifecycle.getInstance().emitTelemetry({ eventName: 'FOOTER_HIDDEN' });
  } else {
    const footer = messages.getMessage('footer', [this.config.bin, releaseNotesPath, HIDE_NOTES, HIDE_FOOTER]);

    this.ux.log(marked.parse(footer));
  }
}
```

2021-11-30 18:43 UTC, iowillhoit approved these changes

2021-11-30 18:43 UTC, merged